import DashboardLayout from "@/components/DashboardLayout";
import { WorkflowStatusBadge } from "@/components/WorkflowStatusBadge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { formatDate, formatPillar } from "@/lib/workflowUi";
import { trpc } from "@/lib/trpc";
import { STAGE_DEFINITIONS, type StageKey } from "@shared/workflow";
import { AlertTriangle, ArrowLeft, Check, ChevronRight, ClipboardCheck, ExternalLink, FileCode2, FileJson, FileText, Film, FlaskConical, ImagePlus, Loader2, Music2, PauseCircle, Play, RefreshCcw, SearchCheck, Send, ShieldCheck, Sparkles, TerminalSquare, Volume2, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

function actionError(error: { message: string }) { toast.error(error.message); }

function ArtifactIcon({ kind }: { kind: string }) {
  if (kind.includes("JSON") || kind.includes("MANIFEST")) return <FileJson className="h-3.5 w-3.5" />;
  if (kind.includes("SCRIPT") || kind.includes("MARKDOWN")) return <FileText className="h-3.5 w-3.5" />;
  if (kind.includes("AUDIO")) return <Volume2 className="h-3.5 w-3.5" />;
  if (kind.includes("IMAGE")) return <ImagePlus className="h-3.5 w-3.5" />;
  return <FileCode2 className="h-3.5 w-3.5" />;
}

function StageIcon({ stageKey }: { stageKey: StageKey }) {
  const icons: Record<StageKey, typeof SearchCheck> = { RESEARCH: SearchCheck, SCRIPT: FileText, AUDIO: Volume2, SCENES: WandSparkles, IMAGES: ImagePlus, MUSIC: Music2, RENDER: Film, REVIEW: ClipboardCheck, PUBLISHING: Send };
  const Icon = icons[stageKey];
  return <Icon className="h-4 w-4" />;
}

export default function ProjectWorkspace() {
  const [, params] = useRoute("/projects/:projectId");
  const [, setLocation] = useLocation();
  const projectId = Number(params?.projectId);
  const projectInput = useMemo(() => ({ projectId }), [projectId]);
  const workspaceQuery = trpc.workflow.get.useQuery(projectInput, { enabled: Number.isFinite(projectId) && projectId > 0 });
  const utils = trpc.useUtils();
  const [researchJson, setResearchJson] = useState("");
  const [showResearchImport, setShowResearchImport] = useState(false);
  const [showMusicForm, setShowMusicForm] = useState(false);
  const [showRenderImport, setShowRenderImport] = useState(false);
  const [showSceneImport, setShowSceneImport] = useState(false);
  const [handoff, setHandoff] = useState<{ title: string; instructions: string } | null>(null);
  const [music, setMusic] = useState({ trackTitle: "", sourceUrl: "", licenseType: "", attributionText: "", commercialUseAllowed: false, contentIdClear: false, evidenceUrl: "" });
  const [render, setRender] = useState({ finalVideoUrl: "", durationSeconds: "", audioSyncPassed: false, blackFramesPassed: false, loudnessPassed: false, subtitlesPassed: false });
  const [sceneImport, setSceneImport] = useState({ sceneId: "", url: "", sourceUrl: "", promptUsed: "", downloadedAt: new Date().toISOString().slice(0, 16) });
  const refresh = () => utils.workflow.get.invalidate(projectInput);

  const researchRequest = trpc.workflow.requestBrowserResearch.useMutation({ onSuccess: result => { setHandoff({ title: "Live browser research handoff", instructions: result.instructions }); toast.success("Browser research handoff created."); refresh(); }, onError: actionError });
  const researchImport = trpc.workflow.importResearch.useMutation({ onSuccess: () => { toast.success("Research package imported and audited."); setShowResearchImport(false); setResearchJson(""); refresh(); }, onError: actionError });
  const scriptGenerate = trpc.workflow.generateScript.useMutation({ onSuccess: () => { toast.success("Versioned script draft created for review."); refresh(); }, onError: actionError });
  const approvalDecision = trpc.workflow.decideApproval.useMutation({ onSuccess: result => { toast.success(result.status === "COMPLETED" ? "Approval recorded; workflow advanced." : "Rejection recorded; stage paused."); refresh(); }, onError: actionError });
  const audioPrepare = trpc.workflow.prepareAudio.useMutation({ onSuccess: result => { toast.success(result.configured ? "Narration manifest is ready to run." : "Narration manifest saved. Gemini configuration is required before generation."); refresh(); }, onError: actionError });
  const audioRun = trpc.workflow.generateGeminiAudio.useMutation({ onSuccess: () => { toast.success("Gemini narration chunks generated."); refresh(); }, onError: actionError });
  const sceneGenerate = trpc.workflow.generateScenePlan.useMutation({ onSuccess: () => { toast.success("Scene plan created."); refresh(); }, onError: actionError });
  const flowRequest = trpc.workflow.requestGoogleFlow.useMutation({ onSuccess: result => { setHandoff({ title: "Google Flow image handoff", instructions: result.instructions }); toast.success("Google Flow handoff prepared."); refresh(); }, onError: actionError });
  const sceneImageImport = trpc.workflow.importSceneImage.useMutation({ onSuccess: result => { toast.success(result.completedAllScenes ? "Scene imported. The image stage is complete." : "Scene image and provenance imported."); setShowSceneImport(false); setSceneImport({ sceneId: "", url: "", sourceUrl: "", promptUsed: "", downloadedAt: new Date().toISOString().slice(0, 16) }); refresh(); }, onError: actionError });
  const musicRecord = trpc.workflow.recordMusicRights.useMutation({ onSuccess: result => { toast.success(result.resolutionStatus === "VERIFIED" ? "Music rights verified." : "Rights record saved; further evidence is required."); setShowMusicForm(false); refresh(); }, onError: actionError });
  const renderManifest = trpc.workflow.createRenderManifest.useMutation({ onSuccess: () => { toast.success("Deterministic FFmpeg render manifest created."); refresh(); }, onError: actionError });
  const renderImport = trpc.workflow.importRenderResult.useMutation({ onSuccess: () => { toast.success("Render QC imported. Final review can now be requested."); setShowRenderImport(false); refresh(); }, onError: actionError });
  const reviewRequest = trpc.workflow.requestReview.useMutation({ onSuccess: () => { toast.success("Final review approval is ready."); refresh(); }, onError: actionError });
  const publishingExport = trpc.workflow.createPublishingExport.useMutation({ onSuccess: () => { toast.success("Publishing export created for final approval."); refresh(); }, onError: actionError });
  const retryStage = trpc.workflow.retryStage.useMutation({ onSuccess: () => { toast.success("Stage resumed from its recorded checkpoint."); refresh(); }, onError: actionError });

  if (workspaceQuery.isLoading) return <DashboardLayout><div className="grid min-h-[65vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-700" /></div></DashboardLayout>;
  if (!workspaceQuery.data) return <DashboardLayout><div className="blueprint-shell mx-auto max-w-3xl py-20 text-center"><h1 className="text-3xl font-black">Project not found</h1><Button className="mt-5" onClick={() => setLocation("/")}>Return to control center</Button></div></DashboardLayout>;
  const workspace = workspaceQuery.data;
  const completed = workspace.stages.filter(stage => stage.status === "COMPLETED").length;
  const progress = Math.round((completed / workspace.stages.length) * 100);
  const approvedScript = workspace.scripts.find(script => script.status === "APPROVED");
  const audioConfigured = Boolean((workspace.stages.find(stage => stage.stageKey === "AUDIO")?.outputManifest as { configured?: boolean } | null)?.configured);

  function importResearch() {
    try {
      const research = JSON.parse(researchJson);
      researchImport.mutate({ projectId, research });
    } catch {
      toast.error("Paste a valid structured research JSON package before importing.");
    }
  }

  function stageAction(stageKey: StageKey) {
    switch (stageKey) {
      case "RESEARCH": return <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => researchRequest.mutate(projectInput)} disabled={researchRequest.isPending}><SearchCheck className="mr-1.5 h-3.5 w-3.5" /> Request browser research</Button><Button size="sm" variant="outline" onClick={() => setShowResearchImport(true)}><FileJson className="mr-1.5 h-3.5 w-3.5" /> Import research JSON</Button></div>;
      case "SCRIPT": return <Button size="sm" onClick={() => scriptGenerate.mutate(projectInput)} disabled={scriptGenerate.isPending}><FileText className="mr-1.5 h-3.5 w-3.5" /> Generate versioned draft</Button>;
      case "AUDIO": return <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => audioPrepare.mutate(projectInput)} disabled={audioPrepare.isPending}><Volume2 className="mr-1.5 h-3.5 w-3.5" /> Prepare narration</Button>{audioConfigured ? <Button size="sm" variant="outline" onClick={() => audioRun.mutate(projectInput)} disabled={audioRun.isPending}><Play className="mr-1.5 h-3.5 w-3.5" /> Run Gemini TTS</Button> : null}</div>;
      case "SCENES": return <Button size="sm" onClick={() => sceneGenerate.mutate(projectInput)} disabled={sceneGenerate.isPending}><WandSparkles className="mr-1.5 h-3.5 w-3.5" /> Create scene plan</Button>;
      case "IMAGES": return <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => flowRequest.mutate(projectInput)} disabled={flowRequest.isPending}><ImagePlus className="mr-1.5 h-3.5 w-3.5" /> Prepare Google Flow handoff</Button>{workspace.scenes.length ? <Button size="sm" variant="outline" onClick={() => setShowSceneImport(true)}><FileJson className="mr-1.5 h-3.5 w-3.5" /> Import scene</Button> : null}</div>;
      case "MUSIC": return <Button size="sm" onClick={() => setShowMusicForm(true)}><Music2 className="mr-1.5 h-3.5 w-3.5" /> Record rights evidence</Button>;
      case "RENDER": return <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => renderManifest.mutate(projectInput)} disabled={renderManifest.isPending}><TerminalSquare className="mr-1.5 h-3.5 w-3.5" /> Create FFmpeg manifest</Button><Button size="sm" variant="outline" onClick={() => setShowRenderImport(true)}><Film className="mr-1.5 h-3.5 w-3.5" /> Import final + QC</Button></div>;
      case "REVIEW": return <Button size="sm" onClick={() => reviewRequest.mutate(projectInput)} disabled={reviewRequest.isPending}><ClipboardCheck className="mr-1.5 h-3.5 w-3.5" /> Request final review</Button>;
      case "PUBLISHING": return <Button size="sm" onClick={() => publishingExport.mutate(projectInput)} disabled={publishingExport.isPending}><Send className="mr-1.5 h-3.5 w-3.5" /> Create publishing export</Button>;
    }
  }

  return (
    <DashboardLayout>
      <div className="blueprint-shell mx-auto max-w-7xl space-y-6 pb-12">
        <button onClick={() => setLocation("/")} className="inline-flex items-center gap-2 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500 transition-colors hover:text-slate-950"><ArrowLeft className="h-3.5 w-3.5" /> Control center</button>
        <section className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white px-6 py-7 shadow-[0_24px_70px_-45px_rgba(15,23,42,0.42)] md:px-8">
          <div className="absolute -right-10 top-3 h-40 w-40 rounded-full border border-cyan-200" /><div className="absolute right-12 top-16 h-16 w-16 rotate-45 border border-pink-200" />
          <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><WorkflowStatusBadge status={workspace.project.status} /><span className="font-mono text-[10px] uppercase tracking-[0.15em] text-slate-400">{formatPillar(workspace.project.contentPillar)} · {workspace.project.audienceLevel}</span></div><h1 className="mt-4 text-3xl font-black leading-[0.98] tracking-[-0.065em] text-slate-950 md:text-5xl">{workspace.project.title}</h1><p className="mt-3 text-sm leading-6 text-slate-600">{workspace.project.topicBrief}</p></div>
            <div className="min-w-56 rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex items-end justify-between"><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Pipeline completion</span><span className="text-2xl font-black tracking-[-0.05em] text-slate-950">{progress}%</span></div><Progress value={progress} className="mt-3 h-2 bg-slate-200" /><p className="mt-2 font-mono text-[10px] text-slate-500">{completed} of {workspace.stages.length} stage gates completed</p></div>
          </div>
        </section>

        <div className="grid gap-6 xl:grid-cols-[1.45fr_0.8fr]">
          <Card className="blueprint-card border-slate-200 bg-white"><CardContent className="p-0"><div className="border-b border-slate-100 px-5 py-4 md:px-6"><div className="eyebrow">Persistent state machine</div><h2 className="mt-1 text-xl font-black tracking-[-0.04em] text-slate-950">Workflow control surface</h2></div><div className="divide-y divide-slate-100">{workspace.stages.map((stage, index) => { const definition = STAGE_DEFINITIONS.find(item => item.key === stage.stageKey)!; const canAct = !["COMPLETED", "CANCELLED", "WAITING_APPROVAL"].includes(stage.status); return <div key={stage.id} className="px-5 py-5 md:px-6"><div className="flex gap-4"><div className="relative flex w-8 shrink-0 justify-center"><div className={`grid h-8 w-8 place-items-center rounded-full border ${stage.status === "COMPLETED" ? "border-emerald-300 bg-emerald-50 text-emerald-700" : stage.status === "RUNNING" ? "border-cyan-300 bg-cyan-50 text-cyan-700" : "border-slate-200 bg-white text-slate-500"}`}><StageIcon stageKey={stage.stageKey} /></div>{index < workspace.stages.length - 1 ? <div className="absolute top-8 h-[calc(100%+20px)] border-l border-dashed border-slate-200" /> : null}</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-semibold text-slate-400">{String(index + 1).padStart(2, "0")}</span><WorkflowStatusBadge status={stage.status} /></div><h3 className="mt-2 text-base font-black tracking-[-0.025em] text-slate-950">{definition.label}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{definition.description}</p></div>{stage.status === "WAITING_APPROVAL" ? <Badge className="w-fit rounded-full border border-fuchsia-200 bg-fuchsia-50 font-mono text-[10px] text-fuchsia-800 hover:bg-fuchsia-50">Decision required</Badge> : null}</div>{stage.pauseReason || stage.failureReason ? <div className="mt-3 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900"><PauseCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />{stage.failureReason ?? stage.pauseReason}</div> : null}<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="font-mono text-[10px] uppercase tracking-[0.08em] text-slate-400">Attempt {stage.attemptCount} · checkpoint {stage.checkpointVersion}</div><div className="flex flex-wrap gap-2">{canAct ? stageAction(stage.stageKey) : null}{["PAUSED", "FAILED"].includes(stage.status) ? <Button size="sm" variant="ghost" onClick={() => retryStage.mutate({ projectId, stageKey: stage.stageKey })} disabled={retryStage.isPending}><RefreshCcw className="mr-1.5 h-3.5 w-3.5" /> Resume</Button> : null}</div></div></div></div></div>; })}</div></CardContent></Card>

          <div className="space-y-6">
            <Card className="blueprint-card border-slate-200 bg-white"><CardContent className="p-5"><div className="eyebrow">Review queue</div><h2 className="mt-1 text-xl font-black tracking-[-0.04em] text-slate-950">Human approvals</h2><div className="mt-4 space-y-3">{workspace.approvals.filter(item => item.decision === "PENDING").length === 0 ? <p className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">No approval decision is waiting right now.</p> : workspace.approvals.filter(item => item.decision === "PENDING").map(approval => { const stage = workspace.stages.find(item => item.id === approval.stageId); return <div key={approval.id} className="rounded-xl border border-fuchsia-100 bg-fuchsia-50/60 p-4"><div className="flex justify-between gap-3"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-fuchsia-700">{approval.approvalType} approval</p><p className="mt-1 text-sm font-bold text-slate-900">{stage ? STAGE_DEFINITIONS.find(definition => definition.key === stage.stageKey)?.label : "Workflow stage"}</p></div><WorkflowStatusBadge status="WAITING_APPROVAL" /></div><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => approvalDecision.mutate({ projectId, approvalId: approval.id, decision: "APPROVED" })} disabled={approvalDecision.isPending}><Check className="mr-1.5 h-3.5 w-3.5" /> Approve</Button><Button size="sm" variant="outline" onClick={() => approvalDecision.mutate({ projectId, approvalId: approval.id, decision: "REJECTED", notes: "Rejected from the workflow dashboard." })} disabled={approvalDecision.isPending}>Reject</Button></div></div>; })}</div></CardContent></Card>
            {workspace.scenes.length ? <Card className="blueprint-card border-slate-200 bg-white"><CardContent className="p-5"><div className="eyebrow">Image tasks</div><h2 className="mt-1 text-xl font-black tracking-[-0.04em] text-slate-950">Google Flow scene queue</h2><ScrollArea className="mt-4 h-60 pr-3"><div className="space-y-2">{workspace.scenes.map(scene => { const imageUrl = (scene.provenance as { url?: string } | null)?.url; return <div key={scene.id} className="rounded-xl border border-slate-100 bg-slate-50/60 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-400">Scene {String(scene.sceneNumber).padStart(2, "0")}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-700">{scene.prompt}</p></div><Badge variant="outline" className="rounded-full font-mono text-[9px]">{scene.status}</Badge></div><div className="mt-3 flex gap-2">{imageUrl ? <a href={imageUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-cyan-700 hover:underline">Open image <ExternalLink className="h-3 w-3" /></a> : null}{!["DOWNLOADED", "APPROVED"].includes(scene.status) ? <Button size="sm" variant="ghost" className="h-7 px-2 text-xs" onClick={() => { setSceneImport({ sceneId: String(scene.id), url: "", sourceUrl: "", promptUsed: scene.prompt, downloadedAt: new Date().toISOString().slice(0, 16) }); setShowSceneImport(true); }}>Import / retry this scene</Button> : null}</div></div>; })}</div></ScrollArea></CardContent></Card> : null}
            <Card className="blueprint-card border-slate-200 bg-white"><CardContent className="p-5"><div className="eyebrow">Active evidence</div><h2 className="mt-1 text-xl font-black tracking-[-0.04em] text-slate-950">Artifacts and manifests</h2><ScrollArea className="mt-4 h-72 pr-3">{workspace.artifacts.length === 0 ? <p className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">Artifacts appear here as evidence enters the workflow.</p> : <div className="space-y-2">{workspace.artifacts.map(artifact => <details key={artifact.id} className="group rounded-xl border border-slate-100 bg-white p-3"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-semibold text-slate-800"><span className="grid h-6 w-6 place-items-center rounded-md bg-cyan-50 text-cyan-700"><ArtifactIcon kind={artifact.kind} /></span><span className="min-w-0 flex-1 truncate">{artifact.title}</span><ChevronRight className="h-4 w-4 text-slate-400 transition-transform group-open:rotate-90" /></summary><div className="mt-3 border-t border-slate-100 pt-3"><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-slate-400">{artifact.kind} · v{artifact.version} · {formatDate(artifact.createdAt)}</p>{artifact.url ? <a href={artifact.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-cyan-700 hover:underline">Open stored artifact <ExternalLink className="h-3 w-3" /></a> : null}{artifact.inlineContent ? <pre className="mt-3 max-h-44 overflow-auto rounded-lg bg-slate-950 p-3 text-[10px] leading-5 text-slate-200">{artifact.inlineContent}</pre> : null}</div></details>)}</div>}</ScrollArea></CardContent></Card>
            <Card className="blueprint-card border-slate-200 bg-white"><CardContent className="p-5"><div className="eyebrow">Agent activity log</div><h2 className="mt-1 text-xl font-black tracking-[-0.04em] text-slate-950">Execution trail</h2><ScrollArea className="mt-4 h-52 pr-3"><div className="space-y-3">{workspace.events.map(event => <div key={event.id} className="border-l-2 border-cyan-200 pl-3"><p className="text-xs leading-5 text-slate-700">{event.message}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[0.1em] text-slate-400">{event.eventType} · {formatDate(event.createdAt)}</p></div>)}</div></ScrollArea></CardContent></Card>
          </div>
        </div>
      </div>

      <Dialog open={showResearchImport} onOpenChange={setShowResearchImport}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Import live research package</DialogTitle><DialogDescription>Paste the structured JSON exported after actively browsing sources. The workflow stores both a JSON audit artifact and a readable Markdown package.</DialogDescription></DialogHeader><Textarea value={researchJson} onChange={event => setResearchJson(event.target.value)} className="min-h-72 font-mono text-xs" placeholder={'{\n  "summary": "...",\n  "sources": [],\n  "claims": [],\n  "contradictions": [],\n  "unknowns": [],\n  "versionSensitiveNotes": []\n}'} /><DialogFooter><Button variant="outline" onClick={() => setShowResearchImport(false)}>Cancel</Button><Button onClick={importResearch} disabled={researchImport.isPending}>{researchImport.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileJson className="mr-2 h-4 w-4" />} Import package</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={showMusicForm} onOpenChange={setShowMusicForm}><DialogContent><DialogHeader><DialogTitle>Record music rights evidence</DialogTitle><DialogDescription>Only verified commercial-use and Content ID evidence can unlock rendering and publishing.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Track title</Label><Input value={music.trackTitle} onChange={event => setMusic({ ...music, trackTitle: event.target.value })} /></div><div className="space-y-2"><Label>Allowlisted source URL</Label><Input type="url" value={music.sourceUrl} onChange={event => setMusic({ ...music, sourceUrl: event.target.value })} /></div><div className="space-y-2"><Label>License type</Label><Input value={music.licenseType} onChange={event => setMusic({ ...music, licenseType: event.target.value })} placeholder="e.g. CC BY 4.0 or source's royalty-free license" /></div><div className="space-y-2"><Label>License evidence URL</Label><Input type="url" value={music.evidenceUrl} onChange={event => setMusic({ ...music, evidenceUrl: event.target.value })} /></div><div className="space-y-2"><Label>Attribution text</Label><Textarea value={music.attributionText} onChange={event => setMusic({ ...music, attributionText: event.target.value })} /></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={music.commercialUseAllowed} onChange={event => setMusic({ ...music, commercialUseAllowed: event.target.checked })} /> Commercial use is explicitly allowed</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={music.contentIdClear} onChange={event => setMusic({ ...music, contentIdClear: event.target.checked })} /> Content ID status is clear</label></div><DialogFooter><Button variant="outline" onClick={() => setShowMusicForm(false)}>Cancel</Button><Button onClick={() => musicRecord.mutate({ projectId, ...music, evidenceUrl: music.evidenceUrl || undefined, attributionText: music.attributionText || undefined })} disabled={musicRecord.isPending}>Save rights record</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={showRenderImport} onOpenChange={setShowRenderImport}><DialogContent><DialogHeader><DialogTitle>Import local render result and QC</DialogTitle><DialogDescription>Run the generated render manifest in your local FFmpeg worker, then import the final MP4 URL or storage path and the required quality checks.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Final MP4 URL</Label><Input type="url" value={render.finalVideoUrl} onChange={event => setRender({ ...render, finalVideoUrl: event.target.value })} /></div><div className="space-y-2"><Label>Final duration (seconds)</Label><Input type="number" value={render.durationSeconds} onChange={event => setRender({ ...render, durationSeconds: event.target.value })} /></div>{[["audioSyncPassed", "Narration and visuals are in sync"],["blackFramesPassed", "No black frames detected"],["loudnessPassed", "Audio level check passed"],["subtitlesPassed", "Subtitle check passed"]].map(([key, label]) => <label key={key} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={render[key as keyof typeof render] as boolean} onChange={event => setRender({ ...render, [key]: event.target.checked })} /> {label}</label>)}</div><DialogFooter><Button variant="outline" onClick={() => setShowRenderImport(false)}>Cancel</Button><Button onClick={() => renderImport.mutate({ projectId, finalVideoUrl: render.finalVideoUrl, durationSeconds: Number(render.durationSeconds), audioSyncPassed: render.audioSyncPassed, blackFramesPassed: render.blackFramesPassed, loudnessPassed: render.loudnessPassed, subtitlesPassed: render.subtitlesPassed })} disabled={renderImport.isPending}>Import QC result</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={showSceneImport} onOpenChange={setShowSceneImport}><DialogContent><DialogHeader><DialogTitle>Import a Google Flow scene image</DialogTitle><DialogDescription>Attach the downloaded image location and the provenance of the generating Google Flow request. Each scene can be imported or retried independently.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Scene</Label><select className="flex h-10 w-full rounded-xl border border-input bg-background px-3 text-sm" value={sceneImport.sceneId} onChange={event => { const selected = workspace.scenes.find(scene => scene.id === Number(event.target.value)); setSceneImport({ ...sceneImport, sceneId: event.target.value, promptUsed: selected?.prompt ?? sceneImport.promptUsed }); }}><option value="">Select a scene</option>{workspace.scenes.map(scene => <option key={scene.id} value={scene.id}>Scene {String(scene.sceneNumber).padStart(2, "0")} · {scene.status}</option>)}</select></div><div className="space-y-2"><Label>Downloaded image URL or storage path</Label><Input type="url" value={sceneImport.url} onChange={event => setSceneImport({ ...sceneImport, url: event.target.value })} /></div><div className="space-y-2"><Label>Google Flow source URL</Label><Input type="url" value={sceneImport.sourceUrl} onChange={event => setSceneImport({ ...sceneImport, sourceUrl: event.target.value })} /></div><div className="space-y-2"><Label>Exact prompt used</Label><Textarea value={sceneImport.promptUsed} onChange={event => setSceneImport({ ...sceneImport, promptUsed: event.target.value })} /></div><div className="space-y-2"><Label>Downloaded at</Label><Input type="datetime-local" value={sceneImport.downloadedAt} onChange={event => setSceneImport({ ...sceneImport, downloadedAt: event.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setShowSceneImport(false)}>Cancel</Button><Button onClick={() => sceneImageImport.mutate({ projectId, sceneId: Number(sceneImport.sceneId), url: sceneImport.url, sourceUrl: sceneImport.sourceUrl, promptUsed: sceneImport.promptUsed, downloadedAt: new Date(sceneImport.downloadedAt).toISOString() })} disabled={sceneImageImport.isPending}>Import scene evidence</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={Boolean(handoff)} onOpenChange={open => !open && setHandoff(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{handoff?.title}</DialogTitle><DialogDescription>This application cannot access a user’s browser session directly. Use the connected browser workflow, then return here to import the generated research or image evidence.</DialogDescription></DialogHeader><ScrollArea className="max-h-[60vh] rounded-xl border border-slate-200 bg-slate-950 p-4"><pre className="whitespace-pre-wrap font-mono text-xs leading-6 text-cyan-50">{handoff?.instructions}</pre></ScrollArea><DialogFooter><Button onClick={() => setHandoff(null)}>Done</Button></DialogFooter></DialogContent></Dialog>
    </DashboardLayout>
  );
}
